name: Code linting CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint:

    name: Code linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: '1.10.4'
          otp-version: '23.0'
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run formatter
        run: |
          make lint.ci
