name: Test Coverage CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-elixir@v1
      with:
        elixir-version: '1.10.4'
        otp-version: '23.0'
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Output Elixir version
      run: elixir --version
    - name: Output PostgreSQL version
      run: psql --version
    - name: Output Node.js version
      run: node --version
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        TZ: ${{ secrets.TZ }}
      run: >
        DB_USERNAME_TEST=${POSTGRES_USER}
        DB_PASSWORD_TEST=${POSTGRES_PASSWORD}
        GITHUB_TOKEN=${GITHUB_TOKEN}
        MIX_ENV=test
        mix coveralls.github
